#!/usr/bin/env bash
#Redirection
sudo apt-get update
sudo apt-get -y install nginx
echo "Holberton School" | sudo tee /var/www/html/index.html
redirect="\\\trewrite ^/redirect_me https://www.google.com permanent;\n"
sudo sed -i "37i $redirect" /etc/nginx/sites-enabled/default
sudo service nginx restart
