#!/usr/bin/env bash
# 7 lines or less
pkill apache2
sudo chown nginx:nginx /etc/nginx/nginx.conf
sudo chmod 600 /etc/nginx/nginx.conf
sudo sed -i "s/80 default_/8080 default_/" /etc/nginx/sites-enabled/default
sudo -u nginx service nginx start
